package forwardDogRules

import model.Diagnostico;
import model.DiagnosticoPreliminar;
import model.EstadoAnimico;
import model.EstadoFisico;
import model.EstadoGeneral;
import model.Sexo;
import model.Perro;


rule "Perro sin enfermedad"
    when
    	$perro: Perro (
        	estadoAnimico.presentaApatiaYTristeza == false, 
        	estadoAnimico.presentaPerdidaDeApetito == false,
        	estadoFisico.presentaDebilidad == false,
        	estadoFisico.presentaDeshidratacion == false,
        	estadoFisico.presentaOjosHundidos == false,
        	estadoFisico.presentaMucosasPalidas == false,
        	estadoFisico.presentaDolorEnPezones == false,
        	estadoFisico.presentaFiebre == false,
        	estadoFisico.presentaAumentoDelRitmoCardiaco == false,
        	estadoFisico.presentaAdelgazamiento == false,
        	estadoFisico.presentaObstruccionIntestinal == false,
        	estadoFisico.presentaAscitis == false,
        	estadoFisico.presentaDolorArticular == false,
        	estadoFisico.presentaRigidezYLimitacionEnMovimientos == false,
        	estadoFisico.presentaInflamacionEnArticulaciones == false,
        	estadoFisico.presentaCrujidosEnArticulaciones == false,
        	estadoGeneral.presentaHecesConSangre == false,
        	estadoGeneral.presentaVomitos == false,
        	estadoGeneral.presentaDiarrea == false,
        	estadoGeneral.presentaHecesBlandas == false,
        	estadoGeneral.presentaTos == false,
        	estadoGeneral.presentaDesmayos == false,
        	estadoGeneral.presentaHemorragiasNasales == false,
        	diagnostico.diagnosticoPreliminar.isa(DiagnosticoPreliminar.NoDeterminado)
        )
    then
    	modify ($perro) {
    	   diagnostico.setDiagnosticoPreliminar(DiagnosticoPreliminar.SinEnfermedad);
    	}
end

rule "Perro con Parvovirus"
    when
    	$perro: Perro (
        	estadoAnimico.presentaApatiaYTristeza == true, 
        	estadoAnimico.presentaPerdidaDeApetito == true,
        	estadoFisico.presentaDebilidad == true,
        	estadoFisico.presentaDeshidratacion == true,
        	estadoFisico.presentaOjosHundidos == true,
        	estadoFisico.presentaMucosasPalidas == true,
        	estadoFisico.presentaFiebre == false,
        	estadoFisico.presentaAumentoDelRitmoCardiaco == false,
        	estadoFisico.presentaAdelgazamiento == false,
        	estadoFisico.presentaObstruccionIntestinal == false,
        	estadoFisico.presentaAscitis == false,
        	estadoFisico.presentaDolorArticular == false,
        	estadoFisico.presentaRigidezYLimitacionEnMovimientos == false,
        	estadoFisico.presentaInflamacionEnArticulaciones == false,
        	estadoFisico.presentaCrujidosEnArticulaciones == false,
        	estadoGeneral.presentaHecesConSangre == true,
        	estadoGeneral.presentaVomitos == true,
        	estadoGeneral.presentaDiarrea == true,
        	estadoGeneral.presentaHecesBlandas == false,
        	estadoGeneral.presentaTos == false,
        	estadoGeneral.presentaDesmayos == false,
        	estadoGeneral.presentaHemorragiasNasales == false,
    		diagnostico.diagnosticoPreliminar.isa(DiagnosticoPreliminar.NoDeterminado)
    	)
    	
    then
    	modify ($perro) {
    		diagnostico.setDiagnosticoPreliminar(DiagnosticoPreliminar.Parvovirus);
    	}
end

rule "Perro con Mastitis"
    when
    	$perro: Perro (
    		sexo.isa(Sexo.Hembra),
        	estadoAnimico.presentaApatiaYTristeza == true, 
        	estadoAnimico.presentaPerdidaDeApetito == true,
        	estadoFisico.presentaDebilidad == false,
        	estadoFisico.presentaDeshidratacion == false,
        	estadoFisico.presentaOjosHundidos == false,
        	estadoFisico.presentaMucosasPalidas == false,
        	estadoFisico.presentaDolorEnPezones == true,
        	estadoFisico.presentaFiebre == true,
        	estadoFisico.presentaAumentoDelRitmoCardiaco == true,
        	estadoFisico.presentaAdelgazamiento == false,
        	estadoFisico.presentaObstruccionIntestinal == false,
        	estadoFisico.presentaAscitis == false,
        	estadoFisico.presentaDolorArticular == false,
        	estadoFisico.presentaRigidezYLimitacionEnMovimientos == false,
        	estadoFisico.presentaInflamacionEnArticulaciones == false,
        	estadoFisico.presentaCrujidosEnArticulaciones == false,
        	estadoGeneral.presentaHecesConSangre == false,
        	estadoGeneral.presentaVomitos == true,
        	estadoGeneral.presentaDiarrea == true,
        	estadoGeneral.presentaHecesBlandas == false,
        	estadoGeneral.presentaTos == false,
        	estadoGeneral.presentaDesmayos == false,
        	estadoGeneral.presentaHemorragiasNasales == false,
    		diagnostico.diagnosticoPreliminar.isa(DiagnosticoPreliminar.NoDeterminado)
    	)
    	
    then
    	modify ($perro) {
    		diagnostico.setDiagnosticoPreliminar(DiagnosticoPreliminar.Mastitis);
    	}	
end

rule "Perro con parásitos intestinales"
    when
    	$perro: Perro (
        	estadoAnimico.presentaApatiaYTristeza == false, 
        	estadoAnimico.presentaPerdidaDeApetito == true,
        	estadoFisico.presentaDebilidad == false,
        	estadoFisico.presentaDeshidratacion == false,
        	estadoFisico.presentaOjosHundidos == false,
        	estadoFisico.presentaMucosasPalidas == false,
        	estadoFisico.presentaDolorEnPezones == false,
        	estadoFisico.presentaFiebre == false,
        	estadoFisico.presentaAumentoDelRitmoCardiaco == false,
        	estadoFisico.presentaAdelgazamiento == true,
        	estadoFisico.presentaObstruccionIntestinal == true,
        	estadoFisico.presentaAscitis == false,
        	estadoFisico.presentaDolorArticular == false,
        	estadoFisico.presentaRigidezYLimitacionEnMovimientos == false,
        	estadoFisico.presentaInflamacionEnArticulaciones == false,
        	estadoFisico.presentaCrujidosEnArticulaciones == false,
        	estadoGeneral.presentaHecesConSangre == false,
        	estadoGeneral.presentaVomitos == true,
        	estadoGeneral.presentaDiarrea == false,
        	estadoGeneral.presentaHecesBlandas == true,
        	estadoGeneral.presentaTos == false,
        	estadoGeneral.presentaDesmayos == false,
        	estadoGeneral.presentaHemorragiasNasales == false,
        	diagnostico.diagnosticoPreliminar.isa(DiagnosticoPreliminar.NoDeterminado)
        )
    then
    	modify ($perro) {
    	   diagnostico.setDiagnosticoPreliminar(DiagnosticoPreliminar.ParasitosIntestinales);
    	}
end

rule "Perro con Gusanos del corazón"
    when
    	$perro: Perro (
        	estadoAnimico.presentaApatiaYTristeza == false, 
        	estadoAnimico.presentaPerdidaDeApetito == true,
        	estadoFisico.presentaDebilidad == false,
        	estadoFisico.presentaDeshidratacion == false,
        	estadoFisico.presentaOjosHundidos == false,
        	estadoFisico.presentaMucosasPalidas == false,
        	estadoFisico.presentaDolorEnPezones == false,
        	estadoFisico.presentaFiebre == false,
        	estadoFisico.presentaAumentoDelRitmoCardiaco == false,
        	estadoFisico.presentaAdelgazamiento == true,
        	estadoFisico.presentaObstruccionIntestinal == false,
        	estadoFisico.presentaAscitis == true,
        	estadoFisico.presentaDolorArticular == false,
        	estadoFisico.presentaRigidezYLimitacionEnMovimientos == false,
        	estadoFisico.presentaInflamacionEnArticulaciones == false,
        	estadoFisico.presentaCrujidosEnArticulaciones == false,
        	estadoGeneral.presentaHecesConSangre == false,
        	estadoGeneral.presentaVomitos == false,
        	estadoGeneral.presentaDiarrea == false,
        	estadoGeneral.presentaHecesBlandas == false,
        	estadoGeneral.presentaTos == true,
        	estadoGeneral.presentaDesmayos == true,
        	estadoGeneral.presentaHemorragiasNasales == true,
        	diagnostico.diagnosticoPreliminar.isa(DiagnosticoPreliminar.NoDeterminado)
        )
    then
    	modify ($perro) {
    	   diagnostico.setDiagnosticoPreliminar(DiagnosticoPreliminar.GusanoDelCorazon);
    	}
end

rule "Perro con Artritis y Atrosis"
    when
    	$perro: Perro (
        	estadoAnimico.presentaApatiaYTristeza == false, 
        	estadoAnimico.presentaPerdidaDeApetito == false,
        	estadoFisico.presentaDebilidad == false,
        	estadoFisico.presentaDeshidratacion == false,
        	estadoFisico.presentaOjosHundidos == false,
        	estadoFisico.presentaMucosasPalidas == false,
        	estadoFisico.presentaDolorEnPezones == false,
        	estadoFisico.presentaFiebre == false,
        	estadoFisico.presentaAumentoDelRitmoCardiaco == false,
        	estadoFisico.presentaAdelgazamiento == false,
        	estadoFisico.presentaObstruccionIntestinal == false,
        	estadoFisico.presentaAscitis == false,
        	estadoFisico.presentaDolorArticular == true,
        	estadoFisico.presentaRigidezYLimitacionEnMovimientos == true,
        	estadoFisico.presentaInflamacionEnArticulaciones == true,
        	estadoFisico.presentaCrujidosEnArticulaciones == true,
        	estadoGeneral.presentaHecesConSangre == false,
        	estadoGeneral.presentaVomitos == false,
        	estadoGeneral.presentaDiarrea == false,
        	estadoGeneral.presentaHecesBlandas == false,
        	estadoGeneral.presentaTos == false,
        	estadoGeneral.presentaDesmayos == false,
        	estadoGeneral.presentaHemorragiasNasales == false,
        	diagnostico.diagnosticoPreliminar.isa(DiagnosticoPreliminar.NoDeterminado)
        )
    then
    	modify ($perro) {
    	   diagnostico.setDiagnosticoPreliminar(DiagnosticoPreliminar.ArtritisYAtrosis);
    	}
end
